### ISSUE TITLE
Multiple nodes config not working

### ISSUE THREAD

**Issue by IgnatLomkov** [fboucquez/symbol-bootstrap#313]
I'm trying to start multiple nodes (by specifying the nodes in the config, for the test it is completely like [this](https://github.com/symbol/symbol-bootstrap/blob/dev/docs/presetGuides.md))
```yaml
nodes:
    - friendlyName: Peer Node 1 custom friendly name
    - friendlyName: Peer Node 2 custom friendly name
      host: 'peer2.custom.hostname'
    - friendlyName: Api Node 1 custom friendly name
      host: 'api1.custom.hostname'
```
and I get an error:

![image](https://user-images.githubusercontent.com/62788754/140624617-7e308a9b-8557-4c05-91ae-633174215df9.png)

Symbol-bootstrap version: 1.0.9
OS: Ubuntu server 18.04
