### ISSUE TITLE
Add arm support

### ISSUE THREAD

**Issue by fboucquez** [fboucquez/symbol-bootstrap#358]
Atm, symbol-bootstrap uses images created with x86/x64 architectures. The docker-compose generated doesn't work on arm machines, like the new m1 Macs. 

In order to implement this, the different arms images would need to (automatically) created. Bootstrap can then detect the local architecture of the machine and select the right arm images when generating the compose file.

The images Bootstrap uses are the following:

```yml
symbolServerImage: symbolplatform/symbol-server:gcc-10-1.0.3.1
symbolRestImage: symbolplatform/symbol-rest:2.4.0
symbolExplorerImage: symbolplatform/symbol-explorer:1.1.0-alpha
symbolFaucetImage: symbolplatform/symbol-faucet:1.0.1-alpha
mongoImage: mongo:4.4.3-bionic
httpsPortalImage: steveltn/https-portal:1.19
```
Some are easier than others to migrate, mongo already supports arm. The trick would be to build and push them automatically.

We may have other issues that I'm not aware of, I think we would need to request node 15+ for, m1 users.
